# Numpy: Numerical Python

## --> Basic package for Data science

Useful link: https://docs.scipy.org/doc/numpy/ <--Manual

Why would you use it?

In [1]:
A = range(1000) #--> list of number from 0 to 99999
#How would you transform all the element to their square?

In [2]:
###let's create a function that transform all the A elements
###to their square
def loop(A):
    B = []
    for i in A:
        B.append(i*i)

In [3]:
%timeit loop(A)

102 µs ± 197 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
##the numpy way:
import numpy

C = numpy.array(A)

%timeit B = C*2

1.52 µs ± 4.85 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Numpy is FAST and SUPER useful to manipulate data

## 1 - The central structure: The *Numpy array*

A numpy array is a homogeneous multidimensional array. It is a table of elements (usually numbers), **all of the same type**. In NumPy, dimensions are called axes.

### How to create a numpy array?

In [6]:
## 1 - from other python structure (list, tuple):
A = [1, 2, 3]
A = numpy.array(A)
print(A, type(A))

[1 2 3] <class 'numpy.ndarray'>


In [8]:
##as I said, all the element are of the same type
##if you create
A = ['a', 1, 'blabla']
A = numpy.array(A)
print(A, type(A))
##it will assume you only have string!

##THE NUMPY ARRAY CONTAINS ELEMENT OF THE SAME TYPE!

['a' '1' 'blabla'] <class 'numpy.ndarray'>


In [14]:
# 2 - from scratch with numpy
A = numpy.arange(1,10,1)
print('A', A)
B = numpy.zeros((10))  ###takes a tuple as argument
print('B', B)
C = numpy.ones((10))
print('C', C)
D = numpy.linspace(1,10,5)
print('D',D)

A [1 2 3 4 5 6 7 8 9]
B [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
D [ 1.    3.25  5.5   7.75 10.  ]


In [27]:
# 3 # From numpy functions
E = numpy.random.randn(10)
print(E, type(E))

[ 1.44760555  0.33683842 -0.75705611  0.24531903 -0.06343505  0.33937861
  1.50213559  0.36593138  1.07077446  0.78619313] <class 'numpy.ndarray'>


In [28]:
print(A.ndim, B.ndim, C.ndim, D.ndim, E.ndim)
print(A.shape, B.shape, C.shape, D.shape, E.shape)
print(A.size, B.size, C.size, D.size, E.size)

1 1 1 1 1
(9,) (10,) (10,) (5,) (10,)
9 10 10 5 10


In [29]:
##creation of Ndimensional array
##from lists
A = [[1, 2, 3],[3,4,5]]
A = numpy.array(A)
print(A, A.ndim, A.shape, A.size)

[[1 2 3]
 [3 4 5]] 2 (2, 3) 6


In [30]:
#from numpy functions
B = numpy.zeros((10,2)) 
print('B', B, B.ndim, B.shape, B.size)

B [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 2 (10, 2) 20


In [31]:
###identity matrix
iD = numpy.eye(3)
print(iD)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
###go from 1D array to 2D array:

A = numpy.arange(9)
print(A)
B = A.reshape(3,3)
print(B)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
###go from 2D to 1D
print(numpy.ravel(B))

[0 1 2 3 4 5 6 7 8]


## 2 - Manipulation

In [34]:
##let's define 2 lists
B = [1,2,3,4,5]
A = [2,3,4,5,6]

In [35]:
##what if you want to create a third list composed
##of the sum of element of the 2 other list?
###and a 4th coreponding to the product of the 2?
A+B

[2, 3, 4, 5, 6, 1, 2, 3, 4, 5]

In [36]:
###here comes numpy:
B = numpy.array([1,2,3,4,5])
A = numpy.array([2,3,4,5,6])

print(A+B)
print(A*B)
print(A/B)  

[ 3  5  7  9 11]
[ 2  6 12 20 30]
[2.         1.5        1.33333333 1.25       1.2       ]


### --> You can do element-wise Mathematical operation with Numpy arrays

In [42]:
##let's define 2 new arrays

B = numpy.array([1,2,3,4,5])
A = numpy.array([2,3,4,5,6,7])

##and multiply them

In [43]:
B*A

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## 3 - What else?

In [59]:
##indexing
A = numpy.arange(16).reshape(4,4)
print('A=numpy.arange(16).reshape(4,4)\n',      A      ,'\n')
print('A[1]=',     A[1]      ,'\n')

A=numpy.arange(16).reshape(4,4)
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

A[1]= [4 5 6 7] 



In [60]:
###change of one line:

A[1] = [12, 14, 15, 16]

print(A)

[[ 0  1  2  3]
 [12 14 15 16]
 [ 8  9 10 11]
 [12 13 14 15]]


In [61]:
A[2] = 1000

print(A)

[[   0    1    2    3]
 [  12   14   15   16]
 [1000 1000 1000 1000]
 [  12   13   14   15]]


In [62]:
###slicing
print('A[:,:2]=\n',     A[:,:2],    '\n')   
## --> I want all the lines, but only the 2 first columns

A[:,:2]=
 [[   0    1]
 [  12   14]
 [1000 1000]
 [  12   13]] 



In [63]:
###min and max
print(A.min())
print(A.max())

0
1000


In [64]:
###addition of number
print('A+1=\n', A+1, '\n')

A+1=
 [[   1    2    3    4]
 [  13   15   16   17]
 [1001 1001 1001 1001]
 [  13   14   15   16]] 



In [67]:
###Want to find a special number?  
print(numpy.where(A+1==1001)) 
##one of my favorite numpy function

(array([2, 2, 2, 2]), array([0, 1, 2, 3]))


In [68]:
##let's go back to lists for a moment
B = [1,2,3,4,5]
A = [2,3,4,5,6]
C = A+B #<---will concatenate them and create a new list
C   

[2, 3, 4, 5, 6, 1, 2, 3, 4, 5]

In [69]:
###How to do that in numpy?
B = numpy.array([1,2,3,4,5])
A = numpy.array([2,3,4,5,6])
C = numpy.concatenate((A,B))
C

array([2, 3, 4, 5, 6, 1, 2, 3, 4, 5])

In [70]:
###YOU CAN SAAAAVE THEEM in your DISK
A = numpy.array(range(10))
numpy.save('A.npy', A)  #<<--save in disk
B = numpy.load('A.npy') #<--load from disk
B==A

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#### Exercice 1:  Create a null (1d array) vector of size 10 but the fifth value which is 1
#### Exercice 2:  Create a 2d 7x7 array with values ranging from 49 to 1
#### Exercice 3:  Create a 2d array 9x9 filled of zeros and change the middle value from 0 to 1
#### Exercice 4:  Create 2d array  5x5 with 2 on the border and 1 inside